# Generated by Django 6.0.7 on 2026-08-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="csvupload",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="csv_uploads/"),
        ),
    ]
