# Generated by Django 5.1 on 2026-06-17 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_resource"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="pdf",
            field=models.FileField(blank=True, null=True, upload_to="blog_media/"),
        ),
        migrations.AddField(
            model_name="blog",
            name="ppt",
            field=models.FileField(blank=True, null=True, upload_to="blog_media/"),
        ),
        migrations.AddField(
            model_name="blog",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="blog_media/"),
        ),
    ]
