# Generated by Django 6.0.6 on 2026-06-20 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_blog_pdf_blog_ppt_blog_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='curriculum',
            field=models.TextField(blank=True, help_text="One module per line, format 'Module Title: Description'. Example: Module 1: Introduction and Fundamentals"),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.TextField(blank=True, help_text="One point per line. Shown as bullet points under 'Prerequisites'."),
        ),
        migrations.AddField(
            model_name='course',
            name='what_youll_learn',
            field=models.TextField(blank=True, help_text="One point per line. Shown as bullet points under 'What You'll Learn'."),
        ),
    ]
