# Generated by Django 6.0.6 on 2026-06-20 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_curriculum_course_prerequisites_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='paper_code',
            field=models.CharField(blank=True, help_text="Subject/paper code, e.g. '0606/23'", max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='question_code',
            field=models.CharField(blank=True, db_index=True, help_text="Auto-generated display code, e.g. '0606/23_Winter_2019_Q10'. Leave blank to auto-generate from paper code, season, year, and question number.", max_length=120),
        ),
        migrations.AddField(
            model_name='question',
            name='question_number',
            field=models.CharField(blank=True, help_text="Question number within the paper, e.g. 'Q10' or '10'", max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='season',
            field=models.CharField(blank=True, choices=[('summer', 'Summer'), ('winter', 'Winter'), ('specimen', 'Specimen')], max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.CharField(blank=True, help_text="Comma-separated topics, e.g. 'Functions, Modulus'", max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='year',
            field=models.IntegerField(blank=True, help_text='e.g. 2019', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='zone',
            field=models.CharField(blank=True, choices=[('', '—'), ('zone_1', 'Zone 1'), ('zone_2', 'Zone 2'), ('zone_3', 'Zone 3')], max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(help_text='Supports inline math using LaTeX delimiters: $x^2+1$ for inline, $$\\frac{a}{b}$$ for a centered block. Rendered with MathJax on the site and rasterized for PDF export.'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('single_choice', 'Single Choice'), ('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('numerical', 'Numerical'), ('matching', 'Matching'), ('structured', 'Structured (multi-part, past paper style)')], max_length=20),
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Untitled Exam', max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized')], default='draft', max_length=20)),
                ('duration_minutes', models.IntegerField(default=60, help_text='Used for the built-in exam timer')),
                ('questions_per_page', models.IntegerField(default=1, help_text='How many questions to show per page in the exported PDF')),
                ('shuffle_questions', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, help_text='Curriculum / Subject this exam is built from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='courses.coursecategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_questions', to='courses.exam')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_links', to='courses.question')),
            ],
            options={
                'ordering': ['order', 'added_at'],
                'unique_together': {('exam', 'question')},
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='questions',
            field=models.ManyToManyField(related_name='exams', through='courses.ExamQuestion', to='courses.question'),
        ),
    ]
