# Generated by Django 6.0.6 on 2026-06-23 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_studentprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Untitled Question List', max_length=200)),
                ('is_admin_curated', models.BooleanField(default=False, help_text='True for lists built by an admin (e.g. shared templates), False for student lists.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, help_text='Curriculum / Subject this list is built from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_lists', to='courses.coursecategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_links', to='courses.question')),
                ('question_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_items', to='courses.questionlist')),
            ],
            options={
                'ordering': ['order', 'added_at'],
                'unique_together': {('question_list', 'question')},
            },
        ),
        migrations.AddField(
            model_name='questionlist',
            name='questions',
            field=models.ManyToManyField(related_name='question_lists', through='courses.QuestionListItem', to='courses.question'),
        ),
    ]
