# Generated by Django 6.0.6 on 2026-07-01 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_discussionpost_discussionreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='equation_images',
            field=models.TextField(blank=True, help_text='JSON list of equation image URLs captured from a Word import (read-only reference).'),
        ),
    ]
