# Generated by Django 6.0.6 on 2026-07-03 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_add_question_equation_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscussionBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=110, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first in the sidebar')),
            ],
            options={
                'verbose_name': 'Discussion Board',
                'verbose_name_plural': 'Discussion Boards',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='discussionpost',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image attached to the post', null=True, upload_to='discussion_images/posts/'),
        ),
        migrations.AddField(
            model_name='discussionreply',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image attached to the reply', null=True, upload_to='discussion_images/replies/'),
        ),
        migrations.AddField(
            model_name='discussionpost',
            name='board',
            field=models.ForeignKey(blank=True, help_text='Which discussion board this post belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='courses.discussionboard'),
        ),
    ]
