# Generated by Django 6.0.6 on 2026-07-23 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_examattempt_examattemptanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_type',
            field=models.CharField(choices=[('single', 'Single'), ('multiple', 'Multiple')], default='single', help_text="Whether one option ('single') or several options ('multiple') can be marked correct.", max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty_level',
            field=models.CharField(blank=True, choices=[('', 'Add difficulty level'), ('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='negative_marks',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Marks deducted for a wrong attempt.', max_digits=6),
        ),
        migrations.AddField(
            model_name='question',
            name='numeric_tolerance',
            field=models.DecimalField(blank=True, decimal_places=3, help_text="Allowed +/- tolerance for 'integer' type answers.", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='partial_marking',
            field=models.BooleanField(default=False, help_text="Award proportional marks for a partially-correct 'multiple' answer instead of all-or-nothing."),
        ),
        migrations.AddField(
            model_name='question',
            name='passage',
            field=models.TextField(blank=True, help_text="Shared comprehension passage this question belongs to (only used for 'comprehension' type questions)."),
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.CharField(blank=True, help_text="Comma-separated tags, e.g. 'Algebra, Grade 10'", max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, help_text="Shown to students as the question 'Solution'."),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('single_choice', 'Single Choice'), ('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('numerical', 'Numerical'), ('matching', 'Matching'), ('structured', 'Structured (multi-part, past paper style)'), ('mcq', 'Multiple Choice Questions'), ('comprehension', 'Comprehension Questions'), ('fill_blank', 'Fill in the Blanks Questions'), ('integer', 'Integer Type Questions')], max_length=20),
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, help_text='Supports basic rich text (HTML).')),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='courses.question')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
