# Generated by Django 5.1.5 on 2026-07-25 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0014_question_answer_type_question_difficulty_level_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="discussionreply",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="discussionreply",
            name="content",
            field=models.TextField(blank=True),
        ),
    ]
