# Generated by Django 6.0.7 on 2026-08-07 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0017_contact_message"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="discussionboard",
            options={
                "ordering": ["order", "name"],
                "verbose_name": "Question Form Board",
                "verbose_name_plural": "Question Form Boards",
            },
        ),
        migrations.AlterModelOptions(
            name="discussionpost",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Question Form Question",
                "verbose_name_plural": "Question Form Questions",
            },
        ),
        migrations.AlterModelOptions(
            name="discussionreply",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Question Form Reply",
                "verbose_name_plural": "Question Form Replies",
            },
        ),
        migrations.AddField(
            model_name="discussionpost",
            name="video_solution_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Optional link to a video solution for this question.",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="discussionreply",
            name="video_solution_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Optional link to a video solution for this answer.",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="video_solution_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Optional link to a video solution (YouTube, Vimeo, Drive, etc.).",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="discussionpost",
            name="board",
            field=models.ForeignKey(
                blank=True,
                help_text="Which topic board this question belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                to="courses.discussionboard",
            ),
        ),
        migrations.AlterField(
            model_name="discussionpost",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Optional image attached to the question",
                null=True,
                upload_to="discussion_images/posts/",
            ),
        ),
        migrations.AlterField(
            model_name="discussionpost",
            name="title",
            field=models.CharField(
                help_text="Short title for the question", max_length=200
            ),
        ),
    ]
