# Generated by Django 6.0.7 on 2026-08-07 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0018_question_discussion_video_solution_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionbank",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="question_banks",
                to="courses.course",
            ),
        ),
    ]
