# Generated by Django 6.0.7 on 2026-08-07 08:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0019_questionbank_course_protect"),
    ]

    operations = [
        migrations.CreateModel(
            name="PastPaper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Display name, e.g. 'Mathematics 0606/23 Summer 2024'",
                        max_length=255,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        db_index=True,
                        help_text="Subject name, e.g. Mathematics, Physics",
                        max_length=150,
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        db_index=True, help_text="Exam year, e.g. 2024"
                    ),
                ),
                (
                    "season",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "—"),
                            ("summer", "Summer"),
                            ("winter", "Winter"),
                            ("specimen", "Specimen"),
                            ("march", "March"),
                            ("june", "June"),
                            ("november", "November"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "paper_code",
                    models.CharField(
                        blank=True,
                        help_text="Optional code, e.g. 0606/23",
                        max_length=50,
                    ),
                ),
                (
                    "pdf",
                    models.FileField(
                        help_text="Full exam paper PDF",
                        upload_to="past_papers/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf"]
                            )
                        ],
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Unpublished papers are hidden from the public Past Papers page",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Category / curriculum (e.g. JEE, CIE IGCSE)",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="past_papers",
                        to="courses.coursecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Past Paper",
                "verbose_name_plural": "Past Papers",
                "ordering": ["-year", "subject", "title"],
            },
        ),
    ]
