# Generated by Django 6.0.7 on 2026-08-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0020_past_paper_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionbank",
            name="subject_title",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Subject title for this bank, e.g. Mathematics, Physics",
                max_length=150,
            ),
        ),
    ]
