# Generated by Django 5.1.5 on 2026-08-08 07:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0021_questionbank_subject_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="pastpaper",
            name="answer_pdf",
            field=models.FileField(
                blank=True,
                help_text="Optional mark scheme / answer sheet PDF linked to this question paper",
                null=True,
                upload_to="past_papers/answers/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="pastpaper",
            name="pdf",
            field=models.FileField(
                help_text="Full exam question paper PDF",
                upload_to="past_papers/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    )
                ],
            ),
        ),
    ]
