# Generated by Django 5.1.5 on 2026-08-08 07:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0022_pastpaper_answer_pdf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="file",
            field=models.FileField(
                help_text="PDF, Word (.doc/.docx), text, or image. View-only for students (no download).",
                upload_to="resources/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "pdf",
                            "doc",
                            "docx",
                            "txt",
                            "png",
                            "jpg",
                            "jpeg",
                            "gif",
                            "webp",
                        ]
                    )
                ],
            ),
        ),
    ]
