# Generated by Django 6.0.7 on 2026-08-12 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0023_resource_file_validators"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="discussionboard",
            options={
                "ordering": ["order", "name"],
                "verbose_name": "Question Forum Board",
                "verbose_name_plural": "Question Forum Boards",
            },
        ),
        migrations.AlterModelOptions(
            name="discussionpost",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Question Forum Question",
                "verbose_name_plural": "Question Forum Questions",
            },
        ),
        migrations.AlterModelOptions(
            name="discussionreply",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Question Forum Reply",
                "verbose_name_plural": "Question Forum Replies",
            },
        ),
        migrations.RemoveField(
            model_name="blog",
            name="ppt",
        ),
    ]
