# Generated by Django 6.0.7 on 2026-08-12 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0024_remove_blog_ppt"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="allow_calculator",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, students can use the on-screen calculator during practice.",
            ),
        ),
    ]
