# Generated by Django 6.0.6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0027_question_hint"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="mobile_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Required at registration. Existing accounts may be empty.",
                max_length=20,
            ),
        ),
        migrations.AlterModelOptions(
            name="studentprofile",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Registered user",
                "verbose_name_plural": "Registered users",
            },
        ),
    ]
